apiVersion: batch/v1
kind: Job
metadata:
  name: grader-matrix
spec:
  template:
    spec:
      containers:
      - name: grader
        image: local-grader-matrix:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "1000m"
            memory: "512Mi"
      restartPolicy: Never
